-- ~/.config/nvim/lua/plugins/transparent.lua
return {
  "xiyaowong/transparent.nvim",
  config = function()
    require("transparent").setup({
      extra_groups = {
        "NormalFloat",
        "FloatBorder",
        "SnacksNormal",
        "SnacksDashboardNormal",
        "WinBar",
        "WinBarNC",
        "StatusLine",
        "StatusLineNC",
        "WinBar",
        "WinBarNC",
        "Normal",
        "NormalNC",
        "TabLine",
        "TabLineFill",
        "TabLineSel",
        "BufferLineFill",
        "BufferLineBackground",
        "BufferLineSeparator",
        "BufferLineTab",
        "BufferLineTabSelected",
        "BufferLineTabSeparator",
        "BufferLineBufferVisible",
        "BufferLineBufferSelected",
        "BufferLineModified",
        "BufferLineModifiedVisible",
        "BufferLineModifiedSelected",
        "BufferLineCloseButton",
        "BufferLineCloseButtonVisible",
        "BufferLineCloseButtonSelected",
        "BufferLineSeparatorVisible",
        "BufferLineSeparatorSelected",
        "BufferLineIndicatorSelected",
        "BufferLineTabSelected",
        "BufferLineNumbersSelected",
      },
    })
  end,
}
